package com.apaza.moises.notevoice.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALARM".
 */
public class Alarm {

    private Long id;
    private Long code;
    private java.util.Date alarmDate;
    private String reason;
    private Boolean status;

    public Alarm() {
    }

    public Alarm(Long id) {
        this.id = id;
    }

    public Alarm(Long id, Long code, java.util.Date alarmDate, String reason, Boolean status) {
        this.id = id;
        this.code = code;
        this.alarmDate = alarmDate;
        this.reason = reason;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCode() {
        return code;
    }

    public void setCode(Long code) {
        this.code = code;
    }

    public java.util.Date getAlarmDate() {
        return alarmDate;
    }

    public void setAlarmDate(java.util.Date alarmDate) {
        this.alarmDate = alarmDate;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

}
