package com.apaza.moises.notevoice.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.apaza.moises.notevoice.database.Alarm;
import com.apaza.moises.notevoice.database.Note;
import com.apaza.moises.notevoice.database.Image;
import com.apaza.moises.notevoice.database.Audio;
import com.apaza.moises.notevoice.database.Message;

import com.apaza.moises.notevoice.database.AlarmDao;
import com.apaza.moises.notevoice.database.NoteDao;
import com.apaza.moises.notevoice.database.ImageDao;
import com.apaza.moises.notevoice.database.AudioDao;
import com.apaza.moises.notevoice.database.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig imageDaoConfig;
    private final DaoConfig audioDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final AlarmDao alarmDao;
    private final NoteDao noteDao;
    private final ImageDao imageDao;
    private final AudioDao audioDao;
    private final MessageDao messageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
        alarmDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        audioDaoConfig = daoConfigMap.get(AudioDao.class).clone();
        audioDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        alarmDao = new AlarmDao(alarmDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);
        audioDao = new AudioDao(audioDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(Alarm.class, alarmDao);
        registerDao(Note.class, noteDao);
        registerDao(Image.class, imageDao);
        registerDao(Audio.class, audioDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        alarmDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
        imageDaoConfig.getIdentityScope().clear();
        audioDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
    }

    public AlarmDao getAlarmDao() {
        return alarmDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

    public AudioDao getAudioDao() {
        return audioDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
